apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: sample-app
  namespace: nginx-ingress
spec:
  host: sample-app.altland-simons.xyz
  routes:
  - path: /dev
    route: dev/sample-app
  - path: /prd
    route: prd/sample-app