apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: sample-app
spec:
  host: hostname
  upstreams:
  - name: sample-app
    service: sample-app
    port: 80
  subroutes:
  - path: /base
    action:
      proxy: 
        upstream: sample-app
        rewritePath: /